#!/bin/sh

# Copyright (C) 2010 David Lee <live4thee@gmail.com>
# Copyright (C) 2010 Qing He <qing.x.he@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

CLANG='/usr/bin/clang -emit-llvm'
LL2CC='/usr/bin/llc -march=cpp'

TMP=`mktemp -t llvm2cpp.XXXXXX`
trap "rm $TMP* 2>/dev/null" 0

$CLANG -c "$@" -o $TMP && $LL2CC $TMP && cat $TMP.cpp
